apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-keeper-cfg-template
  namespace: clickhouse-infra
data:
  config.xml.tpl: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <keeper_server>
        <tcp_port>2181</tcp_port>
        <server_id>{{SERVER_ID}}</server_id>
        <log_storage_path>/var/lib/clickhouse-keeper/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse-keeper/snapshots</snapshot_storage_path>
        <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
        </coordination_settings>
        <raft_configuration>
          <server>
            <id>1</id>
            <hostname>ch-keeper-0.ch-keeper.clickhouse-infra.svc.cluster.local</hostname>
            <port>9444</port>
          </server>
          <server>
            <id>2</id>
            <hostname>ch-keeper-1.ch-keeper.clickhouse-infra.svc.cluster.local</hostname>
            <port>9444</port>
          </server>
          <server>
            <id>3</id>
            <hostname>ch-keeper-2.ch-keeper.clickhouse-infra.svc.cluster.local</hostname>
            <port>9444</port>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>
