apiVersion: v1
kind: Service
metadata:
  name: ch-keeper
  namespace: clickhouse-infra
spec:
  clusterIP: None
  selector:
    app: ch-keeper
  ports:
    - name: zk
      port: 2181
      targetPort: 2181
