apiVersion: v1
kind: Service
metadata:
  name: ch-keeper-0-lb
  namespace: clickhouse-infra
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: ch-keeper-0
  ports:
    - name: zk
      port: 2181
      targetPort: 2181
